name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build server and client
        run: npm run build

      - name: Start the app
        run: npm run start &
        
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
