name: Cypress Component Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  component-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Component Tests
        run: npx cypress run --component