name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build server and client
        run: npm run build

      - name: Start the app
        run: |
          npm run start &
          # Wait for the server to be ready
          while ! curl -s http://localhost:3001; do
            echo "Waiting for server to start..."
            sleep 2
          done

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
